-- VELOX V14 migration: repair Arabic text corrupted by latin1 client imports.
-- Run once with a utf8mb4 client: mysql --default-character-set=utf8mb4 < V14...
-- Only touches rows seeded by V8/V9/V13 (ids listed explicitly).
USE velox_db;

UPDATE stores SET name_ar='جاد' WHERE id=8;
UPDATE stores SET name_ar='أبو شقرة' WHERE id=9;
UPDATE stores SET name_ar='كووك دور' WHERE id=10;
UPDATE stores SET name_ar='فلفلة' WHERE id=11;
UPDATE stores SET name_ar='تي بي إس' WHERE id=12;
UPDATE stores SET name_ar='موري سوشي' WHERE id=13;
UPDATE stores SET name_ar='لابوار' WHERE id=14;
UPDATE stores SET name_ar='هارت أتاك' WHERE id=15;
UPDATE stores SET name_ar='بافلو برجر' WHERE id=16;
UPDATE stores SET name_ar='كوستا كوفي' WHERE id=17;
UPDATE stores SET name_ar='البرنس للمأكولات البحرية' WHERE id=18;
UPDATE stores SET name_ar='أبو السيد' WHERE id=19;
UPDATE stores SET name_ar='بول' WHERE id=20;

UPDATE products SET name_ar='بان كيك بالشوكولاتة', description_ar='بان كيك هش بصوص الشوكولاتة' WHERE id=28;
UPDATE products SET name_ar='برجر كلاسيك', description_ar='برجر لحم بالشيدر مع بطاطس' WHERE id=29;
UPDATE products SET name_ar='بيتزا خضار', description_ar='بيتزا خضار على الحطب، حجم كبير' WHERE id=30;
UPDATE products SET name_ar='ستربس حار', description_ar='وجبة ستربس دجاج حار مقرمش' WHERE id=31;
UPDATE products SET name_ar='سلطة سيزر', description_ar='سلطة سيزر طازجة بقطع الدجاج المشوي' WHERE id=32;
UPDATE products SET name_ar='حذاء كاجوال بني', description_ar='حذاء كاجوال جلد طبيعي' WHERE id=33;
UPDATE products SET name_ar='تريننج شتوي', description_ar='طقم تريننج شتوي تقيل' WHERE id=34;
UPDATE products SET name_ar='كاب كلاسيك أسود', description_ar='كاب رياضي أسود قابل للتعديل' WHERE id=35;
UPDATE products SET name_ar='سنيكرز أحمر', description_ar='سنيكرز خفيف للجري' WHERE id=36;
UPDATE products SET name_ar='عطر لاكوست سبورت', description_ar='عطر فرنسي إصدار سبورت 100 مل' WHERE id=37;
UPDATE products SET name_ar='شاشة سامسونج 55 بوصة', description_ar='شاشة سمارت 4K مقاس 55 بوصة' WHERE id=38;
UPDATE products SET name_ar='سماعات رأس', description_ar='سماعات عازلة للضوضاء' WHERE id=39;
UPDATE products SET name_ar='كاميرا احترافية', description_ar='كاميرا احترافية بعدسة' WHERE id=40;
UPDATE products SET name_ar='فول مدمس', description_ar='فول مدمس بزيت الزيتون والليمون' WHERE id=41;
UPDATE products SET name_ar='طعمية', description_ar='طعمية مقرمشة 6 قطع' WHERE id=42;
UPDATE products SET name_ar='كفتة مشوية', description_ar='كفتة مشوية على الفحم نصف كيلو' WHERE id=43;
UPDATE products SET name_ar='فراخ مشوية', description_ar='فرخة كاملة مشوية على الفحم' WHERE id=44;
UPDATE products SET name_ar='دجاج مقرمش', description_ar='دجاج مقرمش 8 قطع' WHERE id=45;
UPDATE products SET name_ar='بطاطس مقلية', description_ar='بطاطس ذهبية مقرمشة' WHERE id=46;
UPDATE products SET name_ar='فطير مشلتت', description_ar='فطير مشلتت بالعسل' WHERE id=47;
UPDATE products SET name_ar='فتة باللحمة', description_ar='فتة بلدي باللحمة' WHERE id=48;
UPDATE products SET name_ar='كرواسون بالزبدة', description_ar='كرواسون فرنسي بالزبدة' WHERE id=49;
UPDATE products SET name_ar='دونتس', description_ar='دونتس 4 قطع' WHERE id=50;
UPDATE products SET name_ar='سوشي سيت', description_ar='سوشي سيت 18 قطعة' WHERE id=51;
UPDATE products SET name_ar='ساشيمي سلمون', description_ar='ساشيمي سلمون طازج' WHERE id=52;
UPDATE products SET name_ar='جاتوه شوكولاتة', description_ar='جاتوه شوكولاتة بلجيكي' WHERE id=53;
UPDATE products SET name_ar='إكلير شوكولاتة', description_ar='إكلير فرنسي بالشوكولاتة' WHERE id=54;
UPDATE products SET name_ar='دبل سماش برجر', description_ar='دبل برجر لحم مدخن' WHERE id=55;
UPDATE products SET name_ar='بطاطس مقرمشة', description_ar='بطاطس مقرمشة زيادة' WHERE id=56;
UPDATE products SET name_ar='برجر لحم', description_ar='برجر لحم كلاسيك' WHERE id=57;
UPDATE products SET name_ar='هوت دوج', description_ar='ساندوتش هوت دوج مشوي' WHERE id=58;
UPDATE products SET name_ar='لاتيه', description_ar='لاتيه بالحليب' WHERE id=59;
UPDATE products SET name_ar='كابتشينو', description_ar='كابتشينو كلاسيك' WHERE id=60;
UPDATE products SET name_ar='سمك قاروص مشوي', description_ar='قاروص مشوي بالليمون' WHERE id=61;
UPDATE products SET name_ar='جمبري بالثوم', description_ar='جمبري بالثوم على الطريقة الإسبانية' WHERE id=62;
UPDATE products SET name_ar='محشي ورق عنب', description_ar='طبق محشي مشكل' WHERE id=63;
UPDATE products SET name_ar='شيش طاووق', description_ar='شيش طاووق متبل ومشوي' WHERE id=64;
UPDATE products SET name_ar='بان أو شوكولا', description_ar='كرواسون فرنسي بالشوكولاتة' WHERE id=65;
UPDATE products SET name_ar='كلوب ساندوتش', description_ar='كلوب ساندوتش ثلاثي' WHERE id=66;

UPDATE reviews SET comment='أكل ممتاز وتوصيل سريع' WHERE id=1;
UPDATE reviews SET comment='خامات كويسة والأسعار مناسبة' WHERE id=2;
UPDATE reviews SET comment='أجهزة أصلية وضمان حقيقي' WHERE id=3;
UPDATE reviews SET comment='أحلى بيتزا والتوصيل سخن' WHERE id=4;
UPDATE reviews SET comment='تغليف شيك ومنتجات أصلية' WHERE id=5;
UPDATE reviews SET comment='مقاسات مظبوطة وخامة نضيفة' WHERE id=6;
UPDATE reviews SET comment='شاحن سريع وتعامل راقي' WHERE id=7;
UPDATE reviews SET comment='فراخ مقرمشة وتحفة' WHERE id=8;
UPDATE reviews SET comment='فطير بلدي على أصوله' WHERE id=9;
UPDATE reviews SET comment='أحلى كرواسون في مصر' WHERE id=10;
UPDATE reviews SET comment='سوشي طازج وتقديم شيك' WHERE id=11;
UPDATE reviews SET comment='حلويات فاخرة فعلاً' WHERE id=12;
UPDATE reviews SET comment='برجر يستاهل التجربة' WHERE id=13;
UPDATE reviews SET comment='هوت دوج ممتاز' WHERE id=14;
UPDATE reviews SET comment='قهوة مظبوطة وقعدة حلوة' WHERE id=15;
UPDATE reviews SET comment='سمك طازج من البحر' WHERE id=16;
UPDATE reviews SET comment='أكل شرقي أصيل' WHERE id=17;
UPDATE reviews SET comment='مخبوزات فرنسية راقية' WHERE id=18;
UPDATE reviews SET comment='فول وطعمية على أصولها' WHERE id=19;
UPDATE reviews SET comment='مشويات ممتازة' WHERE id=20;
