(function () {
  const STRINGS = {
    ar: {
      'app.name':'VELOX','app.tagline':'كل شيء يوصلك في مكان واحد',
      'nav.toggleTheme':'تبديل الوضع الليلي','nav.toggleLang':'English',
      'login.title':'أهلاً بعودتك','login.subtitle':'سجّل الدخول لمتابعة طلباتك والتسوّق من VELOX.','login.submit':'تسجيل الدخول','login.submitting':'جاري تسجيل الدخول...','login.forgot':'نسيت كلمة المرور؟','login.noAccount':'ليس لديك حساب؟','login.createAccount':'إنشاء حساب جديد','login.error.invalid':'البريد الإلكتروني أو كلمة المرور غير صحيحة.','login.error.generic':'تعذّر تسجيل الدخول الآن، حاول مرة أخرى.','login.success':'تم تسجيل الدخول بنجاح، جاري تحويلك...','login.successSimple':'تم تسجيل الدخول بنجاح.','register.title':'إنشاء حساب جديد','register.subtitle':'انضم إلى VELOX وابدأ الطلب في دقائق.','register.submit':'إنشاء الحساب','register.submitting':'جاري إنشاء الحساب...','register.haveAccount':'لديك حساب بالفعل؟','register.loginLink':'تسجيل الدخول','register.success':'تم إنشاء الحساب بنجاح!','register.successSimple':'تم إنشاء الحساب بنجاح.','register.error.emailTaken':'هذا البريد الإلكتروني مستخدم بالفعل.','register.error.generic':'تعذّر إنشاء الحساب الآن، حاول مرة أخرى.',
      'form.email.label':'البريد الإلكتروني','form.email.placeholder':'name@example.com','form.password.label':'كلمة المرور','form.password.placeholder':'••••••••','form.password.show':'إظهار كلمة المرور','form.password.hide':'إخفاء كلمة المرور','form.confirmPassword.label':'تأكيد كلمة المرور','form.fullName.label':'الاسم الكامل','form.fullName.placeholder':'اكتب اسمك بالكامل','form.phone.label':'رقم الهاتف','form.phone.placeholder':'01xxxxxxxxx','form.governorate.label':'المحافظة'
      ,'form.governorate.BEHEIRA':'البحيرة','form.governorate.KAFR_EL_SHEIKH':'كفر الشيخ','form.governorate.GHARBIA':'الغربية','form.governorate.MENOFIA':'المنوفية','form.governorate.QALYUBIA':'القليوبية','form.governorate.SHARKIA':'الشرقية','form.governorate.DAKAHLIA':'الدقهلية','form.governorate.PORT_SAID':'بورسعيد','form.governorate.ISMAILIA':'الإسماعيلية','form.governorate.SUEZ':'السويس','form.governorate.NORTH_SINAI':'شمال سيناء','form.governorate.SOUTH_SINAI':'جنوب سيناء','form.governorate.FAYOUM':'الفيوم','form.governorate.BENI_SUEF':'بني سويف','form.governorate.MINYA':'المنيا','form.governorate.ASYUT':'أسيوط','form.governorate.SOHAG':'سوهاج','form.governorate.QENA':'قنا','form.governorate.LUXOR':'الأقصر','form.governorate.ASWAN':'أسوان','form.governorate.NEW_VALLEY':'الوادي الجديد','form.governorate.MATROUH':'مطروح','form.governorate.RED_SEA':'البحر الأحمر','form.governorate.QALYUBIA':'القليوبية','form.governorate.CAIRO':'القاهرة','form.governorate.GIZA':'الجيزة','form.governorate.ALEXANDRIA':'الإسكندرية','form.governorate.DAMIETTA':'دمياط','form.governorate.BEHEIRA':'البحيرة','form.governorate.KAFR_EL_SHEIKH':'كفر الشيخ','form.governorate.GHARBIA':'الغربية','form.governorate.MENOFIA':'المنوفية','form.governorate.QALYUBIA':'القليوبية','form.governorate.SHARKIA':'الشرقية','form.governorate.DAKAHLIA':'الدقهلية','form.governorate.PORT_SAID':'بورسعيد','form.governorate.ISMAILIA':'الإسماعيلية','form.governorate.SUEZ':'السويس','form.governorate.NORTH_SINAI':'شمال سيناء','form.governorate.SOUTH_SINAI':'جنوب سيناء','form.governorate.FAYOUM':'الفيوم','form.governorate.BENI_SUEF':'بني سويف','form.governorate.MINYA':'المنيا','form.governorate.ASYUT':'أسيوط','form.governorate.SOHAG':'سوهاج','form.governorate.QENA':'قنا','form.governorate.LUXOR':'الأقصر','form.governorate.ASWAN':'أسوان','form.governorate.NEW_VALLEY':'الوادي الجديد','form.governorate.MATROUH':'مطروح','form.governorate.RED_SEA':'البحر الأحمر',
      'strength.0':'ضعيفة جدًا','strength.1':'ضعيفة','strength.2':'متوسطة','strength.3':'جيدة','strength.4':'قوية','validation.required':'هذا الحقل مطلوب.','validation.email.invalid':'صيغة البريد الإلكتروني غير صحيحة.','validation.password.minLength':'كلمة المرور يجب ألا تقل عن ٨ أحرف.','validation.phone.invalid':'رقم هاتف مصري غير صحيح (مثال: 01012345678).','validation.confirmPassword.mismatch':'كلمتا المرور غير متطابقتين.',
      'home.login':'تسجيل الدخول','home.heroPill':'وصلتك أسرع من المتوقع','home.heroTitle':'كل اللي نفسك فيه،<br><span>أقرب مما تتخيل.</span>','home.heroSubtitle':'تسوّق من مطاعم ومتاجر موثوقة، أضف طلبك للسلة، وإحنا نهتم بالباقي.','home.browseProducts':'ابدأ التسوق','home.locationBtn':'📍 اختر منطقتك','home.trustProducts':'منتج متاح','home.trustStores':'متاجر شريكة','home.trustMinutes':'دقيقة توصيل','home.floatTop':'سرعة + سلاسة','home.floatBottomTitle':'طلبك جاهز','home.floatBottomSub':'بانتظار السائق','home.searchPlaceholder':'ابحث عن منتج، مطعم، أو متجر...','home.emptySearchTitle':'مش لاقيين المنتج ده 😅','home.emptySearchSubtitle':'جرب اسم مختلف، اسم المتجر، أو كلمة أبسط.','product.addButton':'إضافة للسلة','home.categoriesEyebrow':'استكشف بسرعة','home.categoriesTitle':'اختار اللي نفسك فيه','home.viewAll':'عرض الكل','home.productsEyebrow':'مختارات VELOX','home.productsTitle':'كل المنتجات في صفحة واحدة مرتبة وواضحة','home.productsSubtitle':'افتح القسم المناسب وشاهد كل المنتجات، التفاصيل، الصور الكبيرة، والأسعار بدون زحمة في الصفحة الرئيسية.','home.viewAllProducts':'عرض كل المنتجات','home.emptyTitle':'مفيش نتائج بالشكل ده','home.emptySubtitle':'جرّب كلمة بحث تانية أو اختار فئة مختلفة.','home.benefit1Title':'توصيل سريع','home.benefit1Text':'نتابع الطلب من المتجر لحد بابك.','home.benefit2Title':'خيارات أكثر','home.benefit2Text':'أكل، إلكترونيات، واحتياجات يومية.','home.benefit3Title':'تجربة موثوقة','home.benefit3Text':'بيانات حسابك محفوظة في جلسة آمنة.',
      'authModal.eyebrow':'حساب VELOX','authModal.loginTitle':'تسجيل الدخول','authModal.loginSubtitle':'سجّل الدخول علشان نكمل طلبك بسهولة وأمان.','authModal.registerTitle':'إنشاء حساب جديد','authModal.registerSubtitle':'اعمل حسابك في أقل من دقيقة وكمل طلبك فورًا.','authModal.loginTab':'تسجيل الدخول','authModal.registerTab':'حساب جديد','locationModal.eyebrow':'التوصيل عندك','locationModal.title':'اختار المحافظة','locationModal.subtitle':'هنستخدم اختيارك لتصفية المتاجر والمنتجات المناسبة لاحقًا.','cart.eyebrow':'سلتك','cart.title':'مراجعة الطلب','cart.emptyTitle':'السلة فاضية','cart.emptySubtitle':'أضف منتجات من الصفحة الرئيسية وهتظهر هنا.','cart.total':'الإجمالي','cart.checkout':'متابعة لإتمام الطلب','cart.checkoutHint':'سيُطلب تسجيل الدخول عند تأكيد الأوردر فقط.','footer.note':'واجهة جاهزة للربط مع الـBackend وDatabase.','category.all':'الكل','category.food':'أكل ومشروبات','category.electronics':'إلكترونيات','category.fashion':'أزياء','category.grocery':'احتياجات يومية','product.added':'تمت الإضافة للسلة','checkout.loginRequired':'سجّل الدخول أولًا علشان نقدر نأكد الأوردر.','checkout.success':'تم استلام طلبك بنجاح.','checkout.backendHint':'اربط زر التأكيد مع POST /api/orders عند توصيل الـBackend.','location.saved':'تم اختيار المحافظة: {{name}}','cart.quantity':'الكمية','cart.payMethod':'طريقة الدفع','cart.payCash':'كاش عند الاستلام','cart.payWallet':'المحفظة','catalog.backHome':'العودة للرئيسية','catalog.eyebrow':'متجر VELOX','catalog.items':'منتج','catalog.addToCart':'إضافة للسلة',
      'sidebar.quick':'اختصارات سريعة','sidebar.home':'الرئيسية','sidebar.categories':'الأقسام','sidebar.products':'المنتجات','sidebar.cart':'السلة','sidebar.account':'تسجيل الدخول','sidebar.location':'منطقة التوصيل','sidebar.theme':'الوضع الليلي','sidebar.language':'English','sidebar.nav':'التنقل','sidebar.orders':'طلباتي','sidebar.favorites':'المفضلة','sidebar.yourAccount':'حسابك','sidebar.profile':'الحساب الشخصي','sidebar.notifications':'الإشعارات','sidebar.settings':'الضبط','sidebar.support':'المساعدة والتواصل','sidebar.feedback':'الشكاوى والاقتراحات','sidebar.rating':'تقييم التطبيق','home.title':'الصفحة الرئيسية','home.welcomeBack':'أهلاً بك،','home.loggedInAs':'مسجّل الدخول بالبريد','home.comingSoon':'واجهة المتجر متاحة الآن.','home.logout':'تسجيل الخروج',
      'brand.headline':'توصيل أسرع لكل ما تحتاجه','brand.subline':'أكل، أزياء، وإلكترونيات من متاجر موثوقة، مع خيارات توصيل عبر محافظات مصر.','brand.stat1.value':'٣','brand.stat1.label':'فئات منتجات','brand.stat2.value':'٧','brand.stat2.label':'متاجر شريكة','brand.stat3.value':'٢٧','brand.stat3.label':'محافظة متاحة'
    },
    en: {
      'app.name':'VELOX','app.tagline':'All-in-one express delivery','nav.toggleTheme':'Toggle dark mode','nav.toggleLang':'العربية',
      'login.title':'Welcome back','login.subtitle':'Log in to manage orders and shop with VELOX.','login.submit':'Log in','login.submitting':'Logging in...','login.forgot':'Forgot password?','login.noAccount':"Don't have an account?",'login.createAccount':'Create an account','login.error.invalid':'Incorrect email or password.','login.error.generic':"Couldn't log you in right now, please try again.",'login.success':'Logged in successfully.','login.successSimple':'Logged in successfully.','register.title':'Create your account','register.subtitle':'Join VELOX and start ordering in minutes.','register.submit':'Create account','register.submitting':'Creating account...','register.haveAccount':'Already have an account?','register.loginLink':'Log in','register.success':'Account created successfully!','register.successSimple':'Account created successfully.','register.error.emailTaken':'This email is already registered.','register.error.generic':"Couldn't create your account right now, please try again.",
      'form.email.label':'Email','form.email.placeholder':'name@example.com','form.password.label':'Password','form.password.placeholder':'••••••••','form.password.show':'Show password','form.password.hide':'Hide password','form.confirmPassword.label':'Confirm password','form.fullName.label':'Full name','form.fullName.placeholder':'Enter your full name','form.phone.label':'Phone number','form.phone.placeholder':'01xxxxxxxxx','form.governorate.label':'Governorate','form.governorate.CAIRO':'Cairo','form.governorate.GIZA':'Giza','form.governorate.ALEXANDRIA':'Alexandria','form.governorate.DAMIETTA':'Damietta','form.governorate.BEHEIRA':'Beheira','form.governorate.KAFR_EL_SHEIKH':'Kafr El-Sheikh','form.governorate.GHARBIA':'Gharbia','form.governorate.MENOFIA':'Menofia','form.governorate.QALYUBIA':'Qalyubia','form.governorate.SHARKIA':'Sharkia','form.governorate.DAKAHLIA':'Dakahlia','form.governorate.PORT_SAID':'Port Said','form.governorate.ISMAILIA':'Ismailia','form.governorate.SUEZ':'Suez','form.governorate.NORTH_SINAI':'North Sinai','form.governorate.SOUTH_SINAI':'South Sinai','form.governorate.FAYOUM':'Fayoum','form.governorate.BENI_SUEF':'Beni Suef','form.governorate.MINYA':'Minya','form.governorate.ASYUT':'Asyut','form.governorate.SOHAG':'Sohag','form.governorate.QENA':'Qena','form.governorate.LUXOR':'Luxor','form.governorate.ASWAN':'Aswan','form.governorate.NEW_VALLEY':'New Valley','form.governorate.MATROUH':'Matrouh','form.governorate.RED_SEA':'Red Sea',
      'strength.0':'Very weak','strength.1':'Weak','strength.2':'Fair','strength.3':'Good','strength.4':'Strong','validation.required':'This field is required.','validation.email.invalid':'Enter a valid email address.','validation.password.minLength':'Password must be at least 8 characters.','validation.phone.invalid':'Enter a valid Egyptian phone number (e.g. 01012345678).','validation.confirmPassword.mismatch':'Passwords do not match.',
      'home.login':'Log in','home.heroPill':'Faster than expected','home.heroTitle':'Everything you need,<br><span>closer than you think.</span>','home.heroSubtitle':'Shop from trusted restaurants and stores, add items to your cart, and we handle the rest.','home.browseProducts':'Start shopping','home.locationBtn':'📍 Choose area','home.trustProducts':'products','home.trustStores':'partner stores','home.trustMinutes':'min delivery','home.floatTop':'Speed + smoothness','home.floatBottomTitle':'Order ready','home.floatBottomSub':'Waiting for courier','home.searchPlaceholder':'Search products, restaurants, or stores...','home.emptySearchTitle':'We could not find that item 😅','home.emptySearchSubtitle':'Try a shorter word, the store name, or another keyword.','product.addButton':'Add to cart','home.categoriesEyebrow':'Explore quickly','home.categoriesTitle':'What are you in the mood for?','home.viewAll':'View all','home.productsEyebrow':'VELOX picks','home.productsTitle':'All products, neatly organized in one page','home.productsSubtitle':'Open the right section to see every product, larger images, details and prices without crowding the home page.','home.viewAllProducts':'View all products','home.emptyTitle':'No matches found','home.emptySubtitle':'Try another search or choose a different category.','home.benefit1Title':'Fast delivery','home.benefit1Text':'Track your order from store to doorstep.','home.benefit2Title':'More choices','home.benefit2Text':'Food, electronics, fashion and essentials.','home.benefit3Title':'Trusted experience','home.benefit3Text':'Your account data stays in a session only.',
      'authModal.eyebrow':'VELOX account','authModal.loginTitle':'Log in','authModal.loginSubtitle':'Log in so we can complete your order quickly and securely.','authModal.registerTitle':'Create your account','authModal.registerSubtitle':'Create your account in under a minute and continue your order.','authModal.loginTab':'Log in','authModal.registerTab':'Create account','locationModal.eyebrow':'Delivery area','locationModal.title':'Choose governorate','locationModal.subtitle':'We will use this choice to filter relevant stores and products later.','cart.eyebrow':'Your cart','cart.title':'Review order','cart.emptyTitle':'Your cart is empty','cart.emptySubtitle':'Add products from the home page and they will appear here.','cart.total':'Total','cart.checkout':'Continue to checkout','cart.checkoutHint':'Login is requested only when you confirm the order.','footer.note':'Frontend prepared for Backend and Database integration.','category.all':'All','category.food':'Food & Drinks','category.electronics':'Electronics','category.fashion':'Fashion','category.grocery':'Essentials','product.added':'Added to cart','checkout.loginRequired':'Log in first so we can confirm your order.','checkout.success':'Order received successfully.','checkout.backendHint':'Connect confirmation to POST /api/orders when the Backend is ready.','location.saved':'Governorate selected: {{name}}','cart.quantity':'Qty','cart.payMethod':'Payment method','cart.payCash':'Cash on delivery','cart.payWallet':'Wallet','catalog.backHome':'Back home','catalog.eyebrow':'VELOX Store','catalog.items':'products','catalog.addToCart':'Add to cart',
      'sidebar.quick':'Quick shortcuts','sidebar.home':'Home','sidebar.categories':'Categories','sidebar.products':'Products','sidebar.cart':'Cart','sidebar.account':'Log in','sidebar.location':'Delivery area','sidebar.theme':'Dark mode','sidebar.language':'العربية','sidebar.nav':'Navigation','sidebar.orders':'My orders','sidebar.favorites':'Favorites','sidebar.yourAccount':'Your account','sidebar.profile':'Profile','sidebar.notifications':'Notifications','sidebar.settings':'Settings','sidebar.support':'Help & contact','sidebar.feedback':'Complaints & suggestions','sidebar.rating':'Rate the app','home.title':'Home','home.welcomeBack':'Welcome,','home.loggedInAs':'Logged in as','home.comingSoon':'The storefront is live.','home.logout':'Log out',
      'brand.headline':'Faster delivery for everything you need','brand.subline':'Food, fashion and electronics from trusted stores, with delivery-area choices across Egypt.','brand.stat1.value':'3','brand.stat1.label':'product categories','brand.stat2.value':'7','brand.stat2.label':'partner stores','brand.stat3.value':'27','brand.stat3.label':'governorates available'
    }
  };
  const STORAGE_KEY='velox_lang';
  function getLang(){return localStorage.getItem(STORAGE_KEY)||'ar';}
  function translate(key,lang){return (STRINGS[lang]||STRINGS.ar)[key]||key;}
  function applyLanguage(lang){if(!STRINGS[lang])lang='ar';localStorage.setItem(STORAGE_KEY,lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=translate(el.dataset.i18n,lang));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=translate(el.dataset.i18nPlaceholder,lang));document.querySelectorAll('[data-i18n-aria-label]').forEach(el=>el.setAttribute('aria-label',translate(el.dataset.i18nAriaLabel,lang)));document.dispatchEvent(new CustomEvent('velox:langchange',{detail:{lang}}));}
  function toggleLanguage(){applyLanguage(getLang()==='ar'?'en':'ar');}
  window.VeloxI18n={getLang,translate,applyLanguage,toggleLanguage,addStrings};
  function addStrings(lang,dict){if(!STRINGS[lang])STRINGS[lang]={};Object.assign(STRINGS[lang],dict);}
  document.addEventListener('DOMContentLoaded',()=>applyLanguage(getLang()));
})();
