(function () {
  const products = [
    {id:3,nameAr:'علبة كشري عائلية',nameEn:'Koshary Family Box',storeAr:'أبو طارق والشبراوي',storeEn:'Abou Tarek & Shabrawy',category:'food',price:120,glow:'#f2f3ff',image:'assets/images/products/koshary-large.jpg',descAr:'علبة كشري كبيرة تكفي العائلة.',descEn:'Large family meal',badge:''},
    {id:4,nameAr:'طقم تيشيرتات قطن أساسية',nameEn:'Basic Cotton T-Shirt Pack',storeAr:'زارا كاجوال',storeEn:'Zara Casual',category:'fashion',price:450,glow:'#f2f3ff',image:'assets/images/products/tshirt-set.jpg',descAr:'تيشيرتات قطن يومية مريحة.',descEn:'Everyday cotton T-Shirt',badge:''},
    {id:5,nameAr:'آيربودز برو الجيل الثاني',nameEn:'AirPods Pro 2nd Gen',storeAr:'آبل',storeEn:'Apple Flagship Store',category:'electronics',price:11500,glow:'#f2f3ff',image:'assets/images/products/airpods-pro.jpg',descAr:'سماعات آبل اللاسلكية بخاصية إلغاء الضوضاء.',descEn:'Apple AirPods Pro, 2nd generation',badge:''},
    {id:6,nameAr:'طبق مشويات مشكل (1 كجم)',nameEn:'Mixed Grill Platter (1 kg)',storeAr:'أبو طارق والشبراوي',storeEn:'Abou Tarek & Shabrawy',category:'food',price:450,glow:'#f2f3ff',image:'assets/images/products/p06-grill.jpg',descAr:'تشكيلة مشويات شهية بحجم عائلي.',descEn:'Assorted grilled meats, family size',badge:''},
    {id:7,nameAr:'راب شاورما لحم',nameEn:'Beef Shawarma Wrap',storeAr:'أبو طارق والشبراوي',storeEn:'Abou Tarek & Shabrawy',category:'food',price:95,glow:'#f2f3ff',image:'assets/images/products/p07-shawarma.jpg',descAr:'شاورما لحم متبلة داخل راب طازج.',descEn:'Grilled beef shawarma wrap',badge:''},
    {id:8,nameAr:'كريب تشيكن كرانشي',nameEn:'Chicken Crepe Crunchy',storeAr:'أبو طارق والشبراوي',storeEn:'Abou Tarek & Shabrawy',category:'food',price:110,glow:'#f2f3ff',image:'assets/images/products/chicken-crepe-user.jpeg',descAr:'كريب دجاج مقرمش بطعم غني.',descEn:'Crispy chicken crepe',badge:''},
    {id:9,nameAr:'ملوخية مع نصف فرخة',nameEn:'Molokhia with Half Chicken',storeAr:'أبو طارق والشبراوي',storeEn:'Abou Tarek & Shabrawy',category:'food',price:160,glow:'#f2f3ff',image:'assets/images/products/molokhia-half-chicken.jpeg',descAr:'طبق مصري تقليدي بلمسة منزلية.',descEn:'Traditional molokhia served with half chicken',badge:''},
    {id:10,nameAr:'بيتزا سوبر سوبريم',nameEn:'Pizza Super Supreme',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:260,glow:'#f2f3ff',image:'assets/images/products/p10-pizza.jpg',descAr:'بيتزا كبيرة محملة بالإضافات.',descEn:'Loaded supreme pizza, large size',badge:''},
    {id:11,nameAr:'برجر لحم بالمشروم',nameEn:'Double Mushroom Beef Burger',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:180,glow:'#f2f3ff',image:'assets/images/products/p11-burger.jpg',descAr:'دبل برجر لحم مع مشروم وصوص خاص.',descEn:'Double beef burger with mushroom',badge:''},
    {id:12,nameAr:'وجبة ستربس تشيكن',nameEn:'Crispy Chicken Strips Meal',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:165,glow:'#f2f3ff',image:'assets/images/products/chicken-strips-user.jpeg',descAr:'ستربس دجاج مقرمشة مع وجبة كاملة.',descEn:'Crispy chicken strips full meal',badge:''},
    {id:13,nameAr:'مكرونة ألفريدو إيطالي',nameEn:'Italian Pasta Alfredo',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:140,glow:'#f2f3ff',image:'assets/images/products/p13-pasta.jpg',descAr:'مكرونة كريمية بصوص ألفريدو.',descEn:'Creamy Alfredo pasta',badge:''},
    {id:14,nameAr:'خبز بالثوم والجبنة',nameEn:'Cheesy Garlic Bread',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:75,glow:'#f2f3ff',image:'assets/images/products/cheesy-garlic-bread-user.jpeg',descAr:'خبز ثوم دافئ بغطاء جبنة ذائب.',descEn:'Garlic bread topped with cheese',badge:''},
    {id:15,nameAr:'جاكيت جينز كاجوال',nameEn:'Casual Denim Jacket',storeAr:'زارا كاجوال',storeEn:'Zara Casual',category:'fashion',price:1200,glow:'#f2f3ff',image:'assets/images/products/denim-jacket.jpeg',descAr:'جاكيت جينز عملي للستايل اليومي.',descEn:'Everyday denim jacket',badge:''},
    {id:16,nameAr:'قبعة صيفية Bucket Hat',nameEn:'Summer Bucket Hat',storeAr:'زارا كاجوال',storeEn:'Zara Casual',category:'fashion',price:300,glow:'#f2f3ff',image:'assets/images/products/summer-hat-user.jpeg',descAr:'قبعة خفيفة مناسبة لأيام الصيف.',descEn:'Lightweight summer bucket hat',badge:''},
    {id:17,nameAr:'عطر لاكوست فرنسي 100 مل',nameEn:'Lacoste French Perfume (100ml)',storeAr:'لاكوست',storeEn:'Lacoste Luxury',category:'fashion',price:4500,glow:'#f2f3ff',image:'assets/images/products/lacoste-lhomme-user.jpeg',descAr:'عطر أنيق بإطلالة فاخرة.',descEn:'Luxury French fragrance, 100ml',badge:''},
    {id:18,nameAr:'قميص بولو كلاسيك',nameEn:'Classic Croco Polo Shirt',storeAr:'لاكوست',storeEn:'Lacoste Luxury',category:'fashion',price:3800,glow:'#f2f3ff',image:'assets/images/products/p18-polo.jpg',descAr:'قميص بولو بقصة كلاسيكية راقية.',descEn:'Signature croco polo shirt',badge:''},
    {id:19,nameAr:'طقم حزام جلد طبيعي',nameEn:'Genuine Leather Belt Set',storeAr:'لاكوست',storeEn:'Lacoste Luxury',category:'fashion',price:2200,glow:'#f2f3ff',image:'assets/images/products/leather-belt-user.jpeg',descAr:'أحزمة جلد طبيعي بتشطيب فاخر.',descEn:'Premium genuine leather belt set',badge:''},
    {id:20,nameAr:'حذاء Ultraboost للجري',nameEn:'Ultraboost Running Sneakers',storeAr:'أديداس',storeEn:'Adidas Sport',category:'fashion',price:2400,glow:'#f2f3ff',image:'assets/images/products/ultraboost-running.jpeg',descAr:'حذاء رياضي خفيف للأداء اليومي.',descEn:'Performance running sneakers',badge:''},
    {id:21,nameAr:'طقم تريننج رياضي',nameEn:'Athletic Tracksuit Set',storeAr:'أديداس',storeEn:'Adidas Sport',category:'fashion',price:1750,glow:'#f2f3ff',image:'assets/images/products/athletic-tracksuit-user.jpeg',descAr:'طقم عملي للتمرين والحركة.',descEn:'Full athletic tracksuit set',badge:''},
    {id:22,nameAr:'كاب رياضي + أساور',nameEn:'Sport Cap & Wristbands',storeAr:'أديداس',storeEn:'Adidas Sport',category:'fashion',price:450,glow:'#f2f3ff',image:'assets/images/products/sport-cap-wristbands.jpeg',descAr:'إكسسوارات بسيطة تكمل لوكك الرياضي.',descEn:'Sport cap and wristbands set',badge:''},
    {id:23,nameAr:'iPhone 15 Pro Max 256GB',nameEn:'iPhone 15 Pro Max 256GB',storeAr:'آبل',storeEn:'Apple Flagship Store',category:'electronics',price:65000,glow:'#f2f3ff',image:'assets/images/products/iphone-15-pro-max.jpeg',descAr:'هاتف Apple الرائد بسعة 256 جيجابايت.',descEn:'Apple iPhone 15 Pro Max, 256GB',badge:''},
    {id:24,nameAr:'MacBook Air M2 13 بوصة',nameEn:'MacBook Air M2 13-inch',storeAr:'آبل',storeEn:'Apple Flagship Store',category:'electronics',price:52000,glow:'#f2f3ff',image:'assets/images/products/p24-macbook.jpg',descAr:'لابتوب خفيف بشريحة M2.',descEn:'Apple MacBook Air, M2 chip, 13-inch',badge:''},
    {id:25,nameAr:'Samsung Galaxy S24 Ultra',nameEn:'Samsung Galaxy S24 Ultra',storeAr:'سامسونج',storeEn:'Samsung Smart Hub',category:'electronics',price:48000,glow:'#f2f3ff',image:'assets/images/products/p25-s24.jpg',descAr:'هاتف سامسونج الرائد للأداء القوي.',descEn:'Samsung flagship smartphone',badge:''},
    {id:26,nameAr:'Galaxy Watch 6',nameEn:'Smart Watch Galaxy Watch 6',storeAr:'سامسونج',storeEn:'Samsung Smart Hub',category:'electronics',price:8500,glow:'#f2f3ff',image:'assets/images/products/p26-watch.jpg',descAr:'ساعة ذكية لمتابعة النشاط والإشعارات.',descEn:'Samsung Galaxy Watch 6',badge:''},
    {id:27,nameAr:'قاعدة شحن لاسلكية سريعة',nameEn:'Wireless Fast Charging Pad',storeAr:'سامسونج',storeEn:'Samsung Smart Hub',category:'electronics',price:950,glow:'#f2f3ff',image:'assets/images/products/wireless-charger-user.jpeg',descAr:'شحن لاسلكي سريع وعملي للمكتب والمنزل.',descEn:'Samsung wireless fast charging pad',badge:''},
    {id:28,nameAr:'بان كيك بالشوكولاتة',nameEn:'Chocolate Pancakes',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:130,glow:'#f2f3ff',image:'assets/images/products/p28-pancakes.jpg',descAr:'بان كيك هش بصوص الشوكولاتة',descEn:'Fluffy pancakes with chocolate sauce',badge:''},
    {id:29,nameAr:'برجر كلاسيك',nameEn:'Classic Burger',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:190,glow:'#f2f3ff',image:'assets/images/products/p29-burger.jpg',descAr:'برجر لحم بالشيدر مع بطاطس',descEn:'Beef burger with cheddar and fries',badge:''},
    {id:30,nameAr:'بيتزا خضار',nameEn:'Veggie Pizza',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:220,glow:'#f2f3ff',image:'assets/images/products/p30-pizza.jpg',descAr:'بيتزا خضار على الحطب، حجم كبير',descEn:'Wood-fired veggie pizza, large',badge:''},
    {id:31,nameAr:'ستربس حار',nameEn:'Spicy Strips',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:175,glow:'#f2f3ff',image:'assets/images/products/chicken-strips.jpeg',descAr:'وجبة ستربس دجاج حار مقرمش',descEn:'Crispy spicy chicken strips meal',badge:''},
    {id:32,nameAr:'سلطة سيزر',nameEn:'Caesar Salad',storeAr:'أبو طارق والشبراوي',storeEn:'Abou Tarek & Shabrawy',category:'food',price:90,glow:'#f2f3ff',image:'assets/images/products/p32-salad.jpg',descAr:'سلطة سيزر طازجة بقطع الدجاج المشوي',descEn:'Fresh caesar salad with grilled chicken',badge:''},
    {id:33,nameAr:'حذاء كاجوال بني',nameEn:'Brown Casual Shoes',storeAr:'زارا كاجوال',storeEn:'Zara Casual',category:'fashion',price:1450,glow:'#f2f3ff',image:'assets/images/products/casual-shoes-reference.jpeg',descAr:'حذاء كاجوال جلد طبيعي',descEn:'Genuine leather casual shoes',badge:''},
    {id:34,nameAr:'تريننج شتوي',nameEn:'Winter Tracksuit',storeAr:'أديداس',storeEn:'Adidas Sport',category:'fashion',price:1950,glow:'#f2f3ff',image:'assets/images/products/athletic-tracksuit.jpeg',descAr:'طقم تريننج شتوي تقيل',descEn:'Heavy winter training suit',badge:''},
    {id:35,nameAr:'كاب كلاسيك أسود',nameEn:'Classic Black Cap',storeAr:'أديداس',storeEn:'Adidas Sport',category:'fashion',price:300,glow:'#f2f3ff',image:'assets/images/products/sport-caps-gallery.jpeg',descAr:'كاب رياضي أسود قابل للتعديل',descEn:'Black sports cap, adjustable',badge:''},
    {id:36,nameAr:'سنيكرز أحمر',nameEn:'Red Sneakers',storeAr:'أديداس',storeEn:'Adidas Sport',category:'fashion',price:3200,glow:'#f2f3ff',image:'assets/images/products/p36-sneakers.jpg',descAr:'سنيكرز خفيف للجري',descEn:'Light running sneakers',badge:''},
    {id:37,nameAr:'عطر لاكوست سبورت',nameEn:'Lacoste Sport Perfume',storeAr:'لاكوست',storeEn:'Lacoste Luxury',category:'fashion',price:3900,glow:'#f2f3ff',image:'assets/images/products/lacoste-perfume.jpeg',descAr:'عطر فرنسي إصدار سبورت 100 مل',descEn:'Sport edition French perfume 100ml',badge:''},
    {id:38,nameAr:'شاشة سامسونج 55 بوصة',nameEn:'Samsung 55 inch TV',storeAr:'سامسونج',storeEn:'Samsung Smart Hub',category:'electronics',price:22000,glow:'#f2f3ff',image:'assets/images/products/samsung-smart-hub-reference.jpeg',descAr:'شاشة سمارت 4K مقاس 55 بوصة',descEn:'4K smart TV 55 inch',badge:''},
    {id:39,nameAr:'سماعات رأس',nameEn:'Headphones',storeAr:'سامسونج',storeEn:'Samsung Smart Hub',category:'electronics',price:2800,glow:'#f2f3ff',image:'assets/images/products/p39-headphones.jpg',descAr:'سماعات عازلة للضوضاء',descEn:'Noise-cancelling over-ear headphones',badge:''},
    {id:40,nameAr:'كاميرا احترافية',nameEn:'Pro Camera',storeAr:'سامسونج',storeEn:'Samsung Smart Hub',category:'electronics',price:15000,glow:'#f2f3ff',image:'assets/images/products/p40-camera.jpg',descAr:'كاميرا احترافية بعدسة',descEn:'Mirrorless pro camera with lens',badge:''},
    {id:41,nameAr:'فول مدمس',nameEn:'Foul Medames',storeAr:'جاد',storeEn:'Gad',category:'food',price:35,glow:'#f2f3ff',image:'assets/images/products/n08-foul.jpg',descAr:'فول مدمس بزيت الزيتون والليمون',descEn:'Classic foul with olive oil and lemon',badge:''},
    {id:42,nameAr:'طعمية',nameEn:'Taameya',storeAr:'جاد',storeEn:'Gad',category:'food',price:30,glow:'#f2f3ff',image:'assets/images/products/n08-taameya.jpg',descAr:'طعمية مقرمشة 6 قطع',descEn:'Crispy taameya 6 pieces',badge:''},
    {id:43,nameAr:'كفتة مشوية',nameEn:'Grilled Kofta',storeAr:'أبو شقرة',storeEn:'Abu Shakra',category:'food',price:280,glow:'#f2f3ff',image:'assets/images/products/n09-kofta.jpg',descAr:'كفتة مشوية على الفحم نصف كيلو',descEn:'Charcoal grilled kofta half kilo',badge:''},
    {id:44,nameAr:'فراخ مشوية',nameEn:'Grilled Chicken',storeAr:'أبو شقرة',storeEn:'Abu Shakra',category:'food',price:220,glow:'#f2f3ff',image:'assets/images/products/n09-chicken.jpg',descAr:'فرخة كاملة مشوية على الفحم',descEn:'Whole charcoal grilled chicken',badge:''},
    {id:45,nameAr:'دجاج مقرمش',nameEn:'Crispy Chicken',storeAr:'كووك دور',storeEn:'Cook Door',category:'food',price:310,glow:'#f2f3ff',image:'assets/images/products/n10-fried.jpg',descAr:'دجاج مقرمش 8 قطع',descEn:'Crispy chicken 8 pieces bucket',badge:''},
    {id:46,nameAr:'بطاطس مقلية',nameEn:'French Fries',storeAr:'كووك دور',storeEn:'Cook Door',category:'food',price:60,glow:'#f2f3ff',image:'assets/images/products/n10-fries.jpg',descAr:'بطاطس ذهبية مقرمشة',descEn:'Golden crispy fries',badge:''},
    {id:47,nameAr:'فطير مشلتت',nameEn:'Feteer Meshaltet',storeAr:'فلفلة',storeEn:'Felfela',category:'food',price:95,glow:'#f2f3ff',image:'assets/images/products/n11-feteer.jpg',descAr:'فطير مشلتت بالعسل',descEn:'Layered feteer with honey',badge:''},
    {id:48,nameAr:'فتة باللحمة',nameEn:'Meat Fatta',storeAr:'فلفلة',storeEn:'Felfela',category:'food',price:180,glow:'#f2f3ff',image:'assets/images/products/n11-fatta.jpg',descAr:'فتة بلدي باللحمة',descEn:'Traditional fatta with meat',badge:''},
    {id:49,nameAr:'كرواسون بالزبدة',nameEn:'Butter Croissant',storeAr:'تي بي إس',storeEn:'TBS Bakery',category:'food',price:55,glow:'#f2f3ff',image:'assets/images/products/n12-croissant.jpg',descAr:'كرواسون فرنسي بالزبدة',descEn:'French butter croissant',badge:''},
    {id:50,nameAr:'دونتس',nameEn:'Glazed Donuts',storeAr:'تي بي إس',storeEn:'TBS Bakery',category:'food',price:120,glow:'#f2f3ff',image:'assets/images/products/n12-donuts.jpg',descAr:'دونتس 4 قطع',descEn:'Glazed donuts 4 pieces',badge:''},
    {id:51,nameAr:'سوشي سيت',nameEn:'Sushi Set',storeAr:'موري سوشي',storeEn:'Mori Sushi',category:'food',price:650,glow:'#f2f3ff',image:'assets/images/products/n13-sushi.jpg',descAr:'سوشي سيت 18 قطعة',descEn:'Chef special sushi set 18 pieces',badge:''},
    {id:52,nameAr:'ساشيمي سلمون',nameEn:'Salmon Sashimi',storeAr:'موري سوشي',storeEn:'Mori Sushi',category:'food',price:480,glow:'#f2f3ff',image:'assets/images/products/n13-salmon.jpg',descAr:'ساشيمي سلمون طازج',descEn:'Fresh salmon sashimi',badge:''},
    {id:53,nameAr:'جاتوه شوكولاتة',nameEn:'Chocolate Gateau',storeAr:'لابوار',storeEn:'La Poire',category:'food',price:380,glow:'#f2f3ff',image:'assets/images/products/n14-gateau.jpg',descAr:'جاتوه شوكولاتة بلجيكي',descEn:'Belgian chocolate gateau',badge:''},
    {id:54,nameAr:'إكلير شوكولاتة',nameEn:'Chocolate Eclair',storeAr:'لابوار',storeEn:'La Poire',category:'food',price:65,glow:'#f2f3ff',image:'assets/images/products/n14-eclair.jpg',descAr:'إكلير فرنسي بالشوكولاتة',descEn:'French eclair with dark glaze',badge:''},
    {id:55,nameAr:'دبل سماش برجر',nameEn:'Double Smash Burger',storeAr:'هارت أتاك',storeEn:'Hart Attack',category:'food',price:215,glow:'#f2f3ff',image:'assets/images/products/n15-smash.jpg',descAr:'دبل برجر لحم مدخن',descEn:'Double smashed beef burger',badge:''},
    {id:56,nameAr:'بطاطس مقرمشة',nameEn:'Crispy Fries',storeAr:'هارت أتاك',storeEn:'Hart Attack',category:'food',price:70,glow:'#f2f3ff',image:'assets/images/products/n15-fries.jpg',descAr:'بطاطس مقرمشة زيادة',descEn:'Extra crispy fries',badge:''},
    {id:57,nameAr:'برجر لحم',nameEn:'Beef Burger',storeAr:'بافلو برجر',storeEn:'Buffalo Burger',category:'food',price:165,glow:'#f2f3ff',image:'assets/images/products/n16-burger.jpg',descAr:'برجر لحم كلاسيك',descEn:'Classic beef burger',badge:''},
    {id:58,nameAr:'هوت دوج',nameEn:'Hot Dog',storeAr:'بافلو برجر',storeEn:'Buffalo Burger',category:'food',price:95,glow:'#f2f3ff',image:'assets/images/products/n16-hotdog.jpg',descAr:'ساندوتش هوت دوج مشوي',descEn:'Grilled hot dog sandwich',badge:''},
    {id:59,nameAr:'لاتيه',nameEn:'Caffe Latte',storeAr:'كوستا كوفي',storeEn:'Costa Coffee',category:'food',price:85,glow:'#f2f3ff',image:'assets/images/products/n17-latte.jpg',descAr:'لاتيه بالحليب',descEn:'Creamy caffe latte',badge:''},
    {id:60,nameAr:'كابتشينو',nameEn:'Cappuccino',storeAr:'كوستا كوفي',storeEn:'Costa Coffee',category:'food',price:80,glow:'#f2f3ff',image:'assets/images/products/n17-cappuccino.jpg',descAr:'كابتشينو كلاسيك',descEn:'Classic cappuccino',badge:''},
    {id:61,nameAr:'سمك قاروص مشوي',nameEn:'Grilled Sea Bass',storeAr:'البرنس للمأكولات البحرية',storeEn:'El Prince Seafood',category:'food',price:340,glow:'#f2f3ff',image:'assets/images/products/n18-fish.jpg',descAr:'قاروص مشوي بالليمون',descEn:'Grilled sea bass with lemon',badge:''},
    {id:62,nameAr:'جمبري بالثوم',nameEn:'Garlic Shrimp',storeAr:'البرنس للمأكولات البحرية',storeEn:'El Prince Seafood',category:'food',price:390,glow:'#f2f3ff',image:'assets/images/products/n18-shrimp.jpg',descAr:'جمبري بالثوم على الطريقة الإسبانية',descEn:'Spanish garlic shrimp',badge:''},
    {id:63,nameAr:'محشي ورق عنب',nameEn:'Stuffed Vine Leaves',storeAr:'أبو السيد',storeEn:'Abu El Sid',category:'food',price:150,glow:'#f2f3ff',image:'assets/images/products/n19-mahshi.jpg',descAr:'طبق محشي مشكل',descEn:'Mahshi platter',badge:''},
    {id:64,nameAr:'شيش طاووق',nameEn:'Shish Tawook',storeAr:'أبو السيد',storeEn:'Abu El Sid',category:'food',price:230,glow:'#f2f3ff',image:'assets/images/products/n19-shish.jpg',descAr:'شيش طاووق متبل ومشوي',descEn:'Marinated grilled tawook',badge:''},
    {id:65,nameAr:'بان أو شوكولا',nameEn:'Pain au Chocolat',storeAr:'بول',storeEn:'Paul Bakery',category:'food',price:75,glow:'#f2f3ff',image:'assets/images/products/n20-pain.jpg',descAr:'كرواسون فرنسي بالشوكولاتة',descEn:'French chocolate croissant',badge:''},
    {id:66,nameAr:'كلوب ساندوتش',nameEn:'Club Sandwich',storeAr:'بول',storeEn:'Paul Bakery',category:'food',price:140,glow:'#f2f3ff',image:'assets/images/products/n20-club.jpg',descAr:'كلوب ساندوتش ثلاثي',descEn:'Triple club sandwich',badge:''},
    {id:67,nameAr:'شكشوكة',nameEn:'Shakshuka',storeAr:'جاد',storeEn:'Gad',category:'food',price:65,glow:'#f2f3ff',image:'assets/images/products/m08-shakshuka.jpg',descAr:'شكشوكة شرقية بالبيض',descEn:'Oriental shakshuka with eggs',badge:''},
    {id:68,nameAr:'ريش مشوية',nameEn:'Grilled Ribs',storeAr:'أبو شقرة',storeEn:'Abu Shakra',category:'food',price:350,glow:'#f2f3ff',image:'assets/images/products/m09-ribs.jpg',descAr:'ريش مشوية على الفحم',descEn:'Smoky BBQ grilled ribs',badge:''},
    {id:69,nameAr:'تشيكن برجر مقرمش',nameEn:'Crispy Chicken Burger',storeAr:'كووك دور',storeEn:'Cook Door',category:'food',price:145,glow:'#f2f3ff',image:'assets/images/products/m10-chickenburger.jpg',descAr:'ساندوتش دجاج مقرمش',descEn:'Crispy chicken sandwich',badge:''},
    {id:70,nameAr:'أم علي',nameEn:'Om Ali',storeAr:'فلفلة',storeEn:'Felfela',category:'food',price:90,glow:'#f2f3ff',image:'assets/images/products/m11-omali.jpg',descAr:'أم علي بالمكسرات',descEn:'Traditional om ali with nuts',badge:''},
    {id:71,nameAr:'سينابون',nameEn:'Cinnamon Rolls',storeAr:'تي بي إس',storeEn:'TBS Bakery',category:'food',price:110,glow:'#f2f3ff',image:'assets/images/products/m12-cinnabon.jpg',descAr:'سينابون بالقرفة',descEn:'Homemade cinnamon rolls',badge:''},
    {id:72,nameAr:'تمبورا الجمبري',nameEn:'Shrimp Tempura',storeAr:'موري سوشي',storeEn:'Mori Sushi',category:'food',price:320,glow:'#f2f3ff',image:'assets/images/products/m13-tempura.jpg',descAr:'تمبورا جمبري مقرمشة',descEn:'Crispy shrimp tempura',badge:''},
    {id:73,nameAr:'تورتة عيد ميلاد',nameEn:'Birthday Torta',storeAr:'لابوار',storeEn:'La Poire',category:'food',price:550,glow:'#f2f3ff',image:'assets/images/products/m14-torta.jpg',descAr:'تورتة شوكولاتة للمناسبات',descEn:'Celebration chocolate torta',badge:''},
    {id:74,nameAr:'أونيون رينجز',nameEn:'Onion Rings',storeAr:'هارت أتاك',storeEn:'Hart Attack',category:'food',price:80,glow:'#f2f3ff',image:'assets/images/products/m15-onion.jpg',descAr:'حلقات بصل ذهبية',descEn:'Golden onion rings',badge:''},
    {id:75,nameAr:'تشيكن وينجز',nameEn:'Chicken Wings',storeAr:'بافلو برجر',storeEn:'Buffalo Burger',category:'food',price:185,glow:'#f2f3ff',image:'assets/images/products/m16-wings.jpg',descAr:'أجنحة بصوص البافلو',descEn:'Spicy buffalo wings',badge:''},
    {id:76,nameAr:'هوت شوكلت',nameEn:'Hot Chocolate',storeAr:'كوستا كوفي',storeEn:'Costa Coffee',category:'food',price:95,glow:'#f2f3ff',image:'assets/images/products/m17-hotchoc.jpg',descAr:'هوت شوكلت غني',descEn:'Rich hot chocolate',badge:''},
    {id:77,nameAr:'فيليه مشوي',nameEn:'Grilled Fillet',storeAr:'البرنس للمأكولات البحرية',storeEn:'El Prince Seafood',category:'food',price:290,glow:'#f2f3ff',image:'assets/images/products/m18-fillet.jpg',descAr:'فيليه مشوي بالليمون',descEn:'Grilled fish fillet with lemon',badge:''},
    {id:78,nameAr:'كباب أضنة',nameEn:'Adana Kebab',storeAr:'أبو السيد',storeEn:'Abu El Sid',category:'food',price:310,glow:'#f2f3ff',image:'assets/images/products/m19-adana.jpg',descAr:'كباب أضنة حار',descEn:'Spicy adana kebab skewers',badge:''},
    {id:79,nameAr:'دنش بالتفاح',nameEn:'Apple Danish',storeAr:'بول',storeEn:'Paul Bakery',category:'food',price:70,glow:'#f2f3ff',image:'assets/images/products/m20-danish.jpg',descAr:'دنش بالتفاح',descEn:'Glazed apple danish',badge:''},
  ];
  const extraProducts = [
    {id:80,nameAr:'كشري وسط',nameEn:'Medium Koshary',storeAr:'أبو طارق والشبراوي',storeEn:'Abou Tarek & Shabrawy',category:'food',price:65,image:'assets/images/products/koshary-large.jpg',descAr:'كشري مصري بالبصل والدقة.',descEn:'Egyptian koshary with crispy onions',badge:'الأكثر طلباً'},
    {id:81,nameAr:'حواوشي بلدي',nameEn:'Egyptian Hawawshi',storeAr:'أبو طارق والشبراوي',storeEn:'Abou Tarek & Shabrawy',category:'food',price:85,image:'assets/images/products/p06-grill.jpg',descAr:'رغيف بلدي محشو باللحم المتبل.',descEn:'Baladi bread stuffed with seasoned beef',badge:''},
    {id:82,nameAr:'ساندوتش كبدة إسكندراني',nameEn:'Alexandrian Liver Sandwich',storeAr:'أبو طارق والشبراوي',storeEn:'Abou Tarek & Shabrawy',category:'food',price:55,image:'assets/images/products/p07-shawarma.jpg',descAr:'كبدة حارة بالفلفل والثوم.',descEn:'Spicy liver with peppers and garlic',badge:''},
    {id:83,nameAr:'أرز باللبن',nameEn:'Rice Pudding',storeAr:'أبو طارق والشبراوي',storeEn:'Abou Tarek & Shabrawy',category:'food',price:45,image:'assets/images/products/m11-omali.jpg',descAr:'أرز باللبن كريمي بالمكسرات.',descEn:'Creamy rice pudding with nuts',badge:''},
    {id:84,nameAr:'بيتزا بيبروني',nameEn:'Pepperoni Pizza',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:245,image:'assets/images/products/p10-pizza.jpg',descAr:'بيتزا بيبروني وجبنة موتزاريلا.',descEn:'Pepperoni pizza with mozzarella',badge:''},
    {id:85,nameAr:'بيتزا تشيكن رانش',nameEn:'Chicken Ranch Pizza',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:275,image:'assets/images/products/p30-pizza.jpg',descAr:'دجاج مشوي وصوص رانش.',descEn:'Grilled chicken with ranch sauce',badge:'جديد'},
    {id:86,nameAr:'بطاطس بالجبنة',nameEn:'Cheesy Fries',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:110,image:'assets/images/products/n15-fries.jpg',descAr:'بطاطس مقرمشة بصوص الجبنة.',descEn:'Crispy fries with cheese sauce',badge:''},
    {id:87,nameAr:'براوني شوكولاتة',nameEn:'Chocolate Brownie',storeAr:'بافالو وبيتزا هت',storeEn:'Buffalo & Pizza Hut',category:'food',price:85,image:'assets/images/products/n14-gateau.jpg',descAr:'براوني دافئ غني بالشوكولاتة.',descEn:'Warm rich chocolate brownie',badge:''},
    {id:88,nameAr:'فول بالسجق',nameEn:'Foul with Sausage',storeAr:'جاد',storeEn:'Gad',category:'food',price:70,image:'assets/images/products/n08-foul.jpg',descAr:'فول مدمس مع سجق شرقي.',descEn:'Foul medames with oriental sausage',badge:''},
    {id:89,nameAr:'ساندوتش طعمية',nameEn:'Taameya Sandwich',storeAr:'جاد',storeEn:'Gad',category:'food',price:25,image:'assets/images/products/n08-taameya.jpg',descAr:'طعمية وسلطة وطحينة في عيش بلدي.',descEn:'Taameya, salad and tahini in baladi bread',badge:''},
    {id:90,nameAr:'مسقعة',nameEn:'Egyptian Moussaka',storeAr:'جاد',storeEn:'Gad',category:'food',price:55,image:'assets/images/products/m08-shakshuka.jpg',descAr:'باذنجان وفلفل بصلصة الطماطم.',descEn:'Eggplant and peppers in tomato sauce',badge:''},
    {id:91,nameAr:'بطاطس بالبيض',nameEn:'Potatoes with Eggs',storeAr:'جاد',storeEn:'Gad',category:'food',price:50,image:'assets/images/products/n10-fries.jpg',descAr:'بطاطس محمرة مع البيض.',descEn:'Fried potatoes served with eggs',badge:''},
    {id:92,nameAr:'كباب مشوي',nameEn:'Charcoal Kebab',storeAr:'أبو شقرة',storeEn:'Abu Shakra',category:'food',price:390,image:'assets/images/products/n09-kofta.jpg',descAr:'كباب لحم مشوي على الفحم.',descEn:'Charcoal-grilled beef kebab',badge:'مميز'},
    {id:93,nameAr:'حمام محشي',nameEn:'Stuffed Pigeon',storeAr:'أبو شقرة',storeEn:'Abu Shakra',category:'food',price:320,image:'assets/images/products/n09-chicken.jpg',descAr:'حمام محشي بالأرز المتبل.',descEn:'Pigeon stuffed with seasoned rice',badge:''},
    {id:94,nameAr:'مشويات مشكلة',nameEn:'Mixed Grill',storeAr:'أبو شقرة',storeEn:'Abu Shakra',category:'food',price:480,image:'assets/images/products/p06-grill.jpg',descAr:'كباب وكفتة وشيش طاووق.',descEn:'Kebab, kofta and shish tawook',badge:''},
    {id:95,nameAr:'طرب مشوي',nameEn:'Grilled Tarb',storeAr:'أبو شقرة',storeEn:'Abu Shakra',category:'food',price:310,image:'assets/images/products/m09-ribs.jpg',descAr:'طرب بلدي مشوي على الفحم.',descEn:'Traditional charcoal-grilled tarb',badge:''},
    {id:96,nameAr:'سوبر كرانشي',nameEn:'Super Crunchy Sandwich',storeAr:'كووك دور',storeEn:'Cook Door',category:'food',price:185,image:'assets/images/products/m10-chickenburger.jpg',descAr:'دجاج مقرمش حار مع جبنة موتزاريلا.',descEn:'Spicy crispy chicken with mozzarella',badge:'الأكثر طلباً'},
    {id:97,nameAr:'جريل فياجرا',nameEn:'Grilled Viagra',storeAr:'كووك دور',storeEn:'Cook Door',category:'food',price:235,image:'assets/images/products/n18-shrimp.jpg',descAr:'جمبري وكابوريا مشوية بصوصات كووك دور.',descEn:'Grilled shrimp and crab with signature sauces',badge:''},
    {id:98,nameAr:'ساندوتش شيش طاووق',nameEn:'Shish Tawook Sandwich',storeAr:'كووك دور',storeEn:'Cook Door',category:'food',price:160,image:'assets/images/products/n19-shish.jpg',descAr:'شيش طاووق مشوي مع صوص الثوم.',descEn:'Grilled tawook with garlic sauce',badge:''},
    {id:99,nameAr:'بيف فاهيتا',nameEn:'Beef Fajita Sandwich',storeAr:'كووك دور',storeEn:'Cook Door',category:'food',price:195,image:'assets/images/products/p07-shawarma.jpg',descAr:'شرائح لحم وفلفل وجبنة.',descEn:'Beef strips, peppers and cheese',badge:''},
    {id:100,nameAr:'كشري فلفلة',nameEn:'Felfela Koshary',storeAr:'فلفلة',storeEn:'Felfela',category:'food',price:75,image:'assets/images/products/koshary-large.jpg',descAr:'كشري مصري بصلصة فلفلة.',descEn:'Egyptian koshary with Felfela sauce',badge:''},
    {id:101,nameAr:'حواوشي فلفلة',nameEn:'Felfela Hawawshi',storeAr:'فلفلة',storeEn:'Felfela',category:'food',price:110,image:'assets/images/products/p06-grill.jpg',descAr:'حواوشي لحم متبل مخبوز طازج.',descEn:'Fresh-baked seasoned beef hawawshi',badge:''},
    {id:102,nameAr:'ملوخية بلدي',nameEn:'Egyptian Molokhia',storeAr:'فلفلة',storeEn:'Felfela',category:'food',price:85,image:'assets/images/products/molokhia-half-chicken.jpeg',descAr:'ملوخية بالتقلية والثوم.',descEn:'Molokhia with garlic coriander topping',badge:''},
    {id:103,nameAr:'فطار شرقي',nameEn:'Oriental Breakfast',storeAr:'فلفلة',storeEn:'Felfela',category:'food',price:145,image:'assets/images/products/n08-foul.jpg',descAr:'فول وطعمية وجبن وخبز بلدي.',descEn:'Foul, taameya, cheese and baladi bread',badge:''},
    {id:104,nameAr:'كرواسون تركي مدخن',nameEn:'Smoked Turkey Croissant',storeAr:'تي بي إس',storeEn:'TBS Bakery',category:'food',price:125,image:'assets/images/products/n12-croissant.jpg',descAr:'كرواسون بالتركي المدخن والجبنة.',descEn:'Croissant with smoked turkey and cheese',badge:''},
    {id:105,nameAr:'بان أو شوكولا',nameEn:'Pain au Chocolat',storeAr:'تي بي إس',storeEn:'TBS Bakery',category:'food',price:75,image:'assets/images/products/n20-pain.jpg',descAr:'معجنات فرنسية محشوة بالشوكولاتة.',descEn:'French pastry filled with chocolate',badge:''},
    {id:106,nameAr:'تشيز كيك لوتس',nameEn:'Lotus Cheesecake',storeAr:'تي بي إس',storeEn:'TBS Bakery',category:'food',price:145,image:'assets/images/products/n14-gateau.jpg',descAr:'تشيز كيك كريمي ببسكويت لوتس.',descEn:'Creamy cheesecake with Lotus biscuits',badge:''},
    {id:107,nameAr:'دنش قرفة',nameEn:'Cinnamon Danish',storeAr:'تي بي إس',storeEn:'TBS Bakery',category:'food',price:70,image:'assets/images/products/m20-danish.jpg',descAr:'دنش هش بالقرفة.',descEn:'Flaky cinnamon Danish',badge:''},
    {id:108,nameAr:'فيلادلفيا رول 4 قطع',nameEn:'Philadelphia Roll 4 pcs',storeAr:'موري سوشي',storeEn:'Mori Sushi',category:'food',price:228,image:'assets/images/products/n13-sushi.jpg',descAr:'سلمون وكريمة جبنة وأفوكادو.',descEn:'Salmon, cream cheese and avocado',badge:'الأكثر طلباً'},
    {id:109,nameAr:'كريسبي شرمب أفوكادو',nameEn:'Crispy Shrimp Avocado Roll',storeAr:'موري سوشي',storeEn:'Mori Sushi',category:'food',price:217,image:'assets/images/products/m13-tempura.jpg',descAr:'جمبري تمبورا وأفوكادو وترياكي.',descEn:'Shrimp tempura, avocado and teriyaki',badge:''},
    {id:110,nameAr:'نيجيري سلمون',nameEn:'Salmon Nigiri',storeAr:'موري سوشي',storeEn:'Mori Sushi',category:'food',price:115,image:'assets/images/products/n13-salmon.jpg',descAr:'أرز سوشي وسلمون طازج.',descEn:'Sushi rice topped with fresh salmon',badge:''},
    {id:111,nameAr:'شوربة ميسو',nameEn:'Miso Soup',storeAr:'موري سوشي',storeEn:'Mori Sushi',category:'food',price:120,image:'assets/images/products/n18-fish.jpg',descAr:'ميسو وتوفو وواكامي.',descEn:'Miso broth with tofu and wakame',badge:''},
    {id:112,nameAr:'ميل فوي',nameEn:'Mille-Feuille',storeAr:'لابوار',storeEn:'La Poire',category:'food',price:95,image:'assets/images/products/n14-eclair.jpg',descAr:'طبقات باف باستري وكريمة فانيليا.',descEn:'Puff pastry layers with vanilla cream',badge:''},
    {id:113,nameAr:'جاتوه مانجو',nameEn:'Mango Gateau',storeAr:'لابوار',storeEn:'La Poire',category:'food',price:420,image:'assets/images/products/n14-gateau.jpg',descAr:'تورتة كريمة ومانجو طازجة.',descEn:'Cream cake with fresh mango',badge:''},
    {id:114,nameAr:'بيتي فور مشكل',nameEn:'Assorted Petit Four',storeAr:'لابوار',storeEn:'La Poire',category:'food',price:260,image:'assets/images/products/m20-danish.jpg',descAr:'تشكيلة بيتي فور ناعم.',descEn:'Assorted delicate petit four',badge:''},
    {id:115,nameAr:'تشيز كيك توت',nameEn:'Berry Cheesecake',storeAr:'لابوار',storeEn:'La Poire',category:'food',price:130,image:'assets/images/products/m14-torta.jpg',descAr:'تشيز كيك بالتوت.',descEn:'Creamy cheesecake topped with berries',badge:''},
    {id:116,nameAr:'تريبل سماش برجر',nameEn:'Triple Smash Burger',storeAr:'هارت أتاك',storeEn:'Hart Attack',category:'food',price:285,image:'assets/images/products/n15-smash.jpg',descAr:'ثلاث قطع لحم مع جبنة وصوص خاص.',descEn:'Three beef patties with cheese and sauce',badge:'حار'},
    {id:117,nameAr:'تشيكن سماش',nameEn:'Crispy Chicken Smash',storeAr:'هارت أتاك',storeEn:'Hart Attack',category:'food',price:195,image:'assets/images/products/m10-chickenburger.jpg',descAr:'دجاج مقرمش مع كول سلو.',descEn:'Crispy chicken with coleslaw',badge:''},
    {id:118,nameAr:'تشيزي فرايز',nameEn:'Cheesy Fries',storeAr:'هارت أتاك',storeEn:'Hart Attack',category:'food',price:120,image:'assets/images/products/n15-fries.jpg',descAr:'بطاطس بصوص الجبنة والهالبينو.',descEn:'Fries with cheese sauce and jalapeno',badge:''},
    {id:119,nameAr:'موتزاريلا ستيكس',nameEn:'Mozzarella Sticks',storeAr:'هارت أتاك',storeEn:'Hart Attack',category:'food',price:135,image:'assets/images/products/m15-onion.jpg',descAr:'أصابع موتزاريلا مقلية.',descEn:'Crispy fried mozzarella sticks',badge:''},
    {id:120,nameAr:'أولد سكول',nameEn:'Old School Burger',storeAr:'بافلو برجر',storeEn:'Buffalo Burger',category:'food',price:275,image:'assets/images/products/n16-burger.jpg',descAr:'برجر لحم بصوص بافلو وجبنة شيدر.',descEn:'Beef burger with Buffalo sauce and cheddar',badge:'الأكثر طلباً'},
    {id:121,nameAr:'تشولوز',nameEn:"Cholo's Burger",storeAr:'بافلو برجر',storeEn:'Buffalo Burger',category:'food',price:275,image:'assets/images/products/p29-burger.jpg',descAr:'هالبينو وصوص بافلو وشيدر.',descEn:'Jalapeno, Buffalo sauce and cheddar',badge:''},
    {id:122,nameAr:'شيتاكي مشروم',nameEn:'Shiitake Mushroom Burger',storeAr:'بافلو برجر',storeEn:'Buffalo Burger',category:'food',price:295,image:'assets/images/products/p11-burger.jpg',descAr:'مشروم سوتيه وشيدر ومايونيز.',descEn:'Sauteed mushroom, cheddar and mayonnaise',badge:''},
    {id:123,nameAr:'تشيكن باستر',nameEn:'Chicken Buster',storeAr:'بافلو برجر',storeEn:'Buffalo Burger',category:'food',price:180,image:'assets/images/products/m16-wings.jpg',descAr:'ستربس دجاج بصوص بافلو وشيدر.',descEn:'Chicken strips with Buffalo sauce and cheddar',badge:''},
    {id:124,nameAr:'فلات وايت',nameEn:'Flat White',storeAr:'كوستا كوفي',storeEn:'Costa Coffee',category:'food',price:105,image:'assets/images/products/n17-latte.jpg',descAr:'إسبريسو مزدوج وحليب مبخر.',descEn:'Double espresso with steamed milk',badge:''},
    {id:125,nameAr:'سبانيش لاتيه',nameEn:'Spanish Latte',storeAr:'كوستا كوفي',storeEn:'Costa Coffee',category:'food',price:135,image:'assets/images/products/n17-cappuccino.jpg',descAr:'لاتيه بالحليب المكثف.',descEn:'Latte sweetened with condensed milk',badge:'جديد'},
    {id:126,nameAr:'آيس كراميل لاتيه',nameEn:'Iced Caramel Latte',storeAr:'كوستا كوفي',storeEn:'Costa Coffee',category:'food',price:140,image:'assets/images/products/n17-latte.jpg',descAr:'قهوة مثلجة بصوص الكراميل.',descEn:'Iced coffee with caramel sauce',badge:''},
    {id:127,nameAr:'براوني شوكولاتة',nameEn:'Chocolate Brownie',storeAr:'كوستا كوفي',storeEn:'Costa Coffee',category:'food',price:95,image:'assets/images/products/n14-gateau.jpg',descAr:'براوني غني مناسب مع القهوة.',descEn:'Rich brownie perfect with coffee',badge:''},
    {id:128,nameAr:'جمبري مشوي',nameEn:'Grilled Shrimp',storeAr:'البرنس للمأكولات البحرية',storeEn:'El Prince Seafood',category:'food',price:450,image:'assets/images/products/n18-shrimp.jpg',descAr:'جمبري مشوي بالليمون والثوم.',descEn:'Grilled shrimp with lemon and garlic',badge:''},
    {id:129,nameAr:'أرز صيادية',nameEn:'Sayadia Rice',storeAr:'البرنس للمأكولات البحرية',storeEn:'El Prince Seafood',category:'food',price:75,image:'assets/images/products/n18-fish.jpg',descAr:'أرز صيادية بالبصل والتوابل.',descEn:'Seasoned sayadia rice with onions',badge:''},
    {id:130,nameAr:'كاليماري مقلي',nameEn:'Fried Calamari',storeAr:'البرنس للمأكولات البحرية',storeEn:'El Prince Seafood',category:'food',price:320,image:'assets/images/products/m13-tempura.jpg',descAr:'حلقات كاليماري مقرمشة.',descEn:'Crispy fried calamari rings',badge:''},
    {id:131,nameAr:'شوربة سي فود',nameEn:'Seafood Soup',storeAr:'البرنس للمأكولات البحرية',storeEn:'El Prince Seafood',category:'food',price:170,image:'assets/images/products/m18-fillet.jpg',descAr:'شوربة كريمية بالمأكولات البحرية.',descEn:'Creamy mixed seafood soup',badge:''},
    {id:132,nameAr:'ملوخية بالأرانب',nameEn:'Molokhia with Rabbit',storeAr:'أبو السيد',storeEn:'Abu El Sid',category:'food',price:295,image:'assets/images/products/molokhia-half-chicken.jpeg',descAr:'ملوخية مصرية مع لحم الأرانب.',descEn:'Egyptian molokhia served with rabbit',badge:'مميز'},
    {id:133,nameAr:'شركسية بالدجاج',nameEn:'Circassian Chicken',storeAr:'أبو السيد',storeEn:'Abu El Sid',category:'food',price:260,image:'assets/images/products/n19-shish.jpg',descAr:'دجاج بصوص الجوز الكريمي.',descEn:'Chicken with creamy walnut sauce',badge:''},
    {id:134,nameAr:'أرز معمر',nameEn:'Baked Creamy Rice',storeAr:'أبو السيد',storeEn:'Abu El Sid',category:'food',price:110,image:'assets/images/products/n19-mahshi.jpg',descAr:'أرز معمر فلاحي بالقشطة.',descEn:'Traditional baked rice with cream',badge:''},
    {id:135,nameAr:'كفتة أبو السيد',nameEn:'Abu El Sid Kofta',storeAr:'أبو السيد',storeEn:'Abu El Sid',category:'food',price:285,image:'assets/images/products/n09-kofta.jpg',descAr:'كفتة مشوية بالتتبيلة المصرية.',descEn:'Grilled kofta with Egyptian seasoning',badge:''},
    {id:136,nameAr:'باجيت دجاج سيزر',nameEn:'Chicken Caesar Baguette',storeAr:'بول',storeEn:'Paul Bakery',category:'food',price:185,image:'assets/images/products/n20-club.jpg',descAr:'دجاج وسيزر في باجيت فرنسي.',descEn:'Chicken Caesar filling in a French baguette',badge:''},
    {id:137,nameAr:'كرواسون باللوز',nameEn:'Almond Croissant',storeAr:'بول',storeEn:'Paul Bakery',category:'food',price:105,image:'assets/images/products/n12-croissant.jpg',descAr:'كرواسون باللوز وكريمة اللوز.',descEn:'Croissant with almonds and almond cream',badge:''},
    {id:138,nameAr:'كيش لورين',nameEn:'Quiche Lorraine',storeAr:'بول',storeEn:'Paul Bakery',category:'food',price:160,image:'assets/images/products/n20-pain.jpg',descAr:'كيش فرنسي بالجبنة واللحم المدخن.',descEn:'French quiche with cheese and smoked beef',badge:''},
    {id:139,nameAr:'تارت ليمون',nameEn:'Lemon Tart',storeAr:'بول',storeEn:'Paul Bakery',category:'food',price:120,image:'assets/images/products/m20-danish.jpg',descAr:'تارت ليمون بكريمة خفيفة.',descEn:'Tangy lemon tart with light cream',badge:''}
  ].map((p)=>({glow:'#f2f3ff',...p}));
  products.push(...extraProducts);
  const foodCount=products.filter((p)=>p.category==='food').length;
  let categories=[
    {id:'all',icon:'✦',titleKey:'category.all',descAr:`كل المختارات — ${products.length} منتج`,descEn:`All picks — ${products.length} products`,tint:'#e9ecff'},
    {id:'food',icon:'🍽️',titleKey:'category.food',descAr:`${foodCount} وجبة ومشروبات`,descEn:`${foodCount} meals & drinks`,tint:'#fff0d9'},
    {id:'electronics',icon:'⌁',titleKey:'category.electronics',descAr:'9 أجهزة وتقنيات',descEn:'9 tech products',tint:'#e9e4ff'},
    {id:'fashion',icon:'◈',titleKey:'category.fashion',descAr:'14 قطعة وإكسسوار',descEn:'14 fashion picks',tint:'#ffe8f2'}
  ];
  function getProducts(){return products.slice();}
  function getCategories(){return categories.slice();}
  function replaceCategories(next){
    if (!Array.isArray(next) || !next.length) return;
    categories = next.map((c) => ({
      id: c.id ?? c.code ?? c.category,
      icon: c.icon ?? '◈',
      titleKey: c.titleKey ?? (c.id ? `category.${c.id}` : 'category.all'),
      descAr: c.descAr ?? c.descriptionAr ?? '',
      descEn: c.descEn ?? c.descriptionEn ?? '',
      tint: c.tint ?? '#e9ecff'
    })).filter((c) => c.id);
  }
  async function loadCatalog(){
    const cfg=window.VELOX_CONFIG;
    if(cfg.USE_MOCK_API) return {products:getProducts(),categories:getCategories()};
    const [productData, categoryData]=await Promise.all([window.VeloxApiClient.request(cfg.ENDPOINTS.products),window.VeloxApiClient.request(cfg.ENDPOINTS.categories)]);
    const products = Array.isArray(productData)?productData:(productData.products||[]);
    const categories = Array.isArray(categoryData)?categoryData:(categoryData.categories||[]);
    // Update category counts from real product data
    const updatedCategories = categories.map(cat => {
      if (cat.id === 'all') {
        return {...cat, descAr: `كل المنتجات — ${products.length} منتج`, descEn: `All products — ${products.length} products`};
      }
      const count = products.filter(p => p.category === cat.id).length;
      return {...cat, descAr: cat.descAr.replace(/\d+/, count), descEn: cat.descEn.replace(/\d+/, count)};
    });
    return {products, categories: updatedCategories};
  }
  function formatPrice(value){
    const formatted = new Intl.NumberFormat('en-US', {maximumFractionDigits: 0}).format(value);
    return formatted + ' EGP';
  }
  window.VeloxCatalogService={getProducts,getCategories,replaceCategories,loadCatalog,formatPrice};
})();
